Tests: avoid traceback seen in tests
This was not causing tests to fail but was disconcerting when looking
at test logs, which contained these errors:

 ERROR    zigpy.zcl:util.py:293 [0x1234:1:0xef00] Traceback (most recent call last):
  File "zigpy/device.py", line 265, in request
    result, msg = await self._application.request(
 ValueError: not enough values to unpack (expected 2, got 0)

The fix ensures that a sent request to the mock app returns a
valid return tuple instead of a mock, which cannot be unpacked and
causes the traceback.